version: '0.1.0'
services:
  app:
    build: .
    image: tianmalu/test1
    ports:
     - "8080:3030"
    environment:
     - DATABASE_URI=mongodb://mongodb:27017
    depends_on:
     - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"